version: '3'
services:

  redis1:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=asdf
      - CLIENTPORT=6379
      - MASTERPORT=
      - CLIENTHOST=10.0.2.15
      - MASTERHOST=
    volumes:
      - "../../redis-data/redis1:/data"
    restart: always

  redis2:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=asdf
      - CLIENTPORT=6380
      - MASTERPORT=6379
      - CLIENTHOST=10.0.2.15
      - MASTERHOST=10.0.2.15
    volumes:
      - "../../redis-data/redis2:/data"
    restart: always

  redis3:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=asdf
      - CLIENTPORT=6381
      - MASTERPORT=6379
      - CLIENTHOST=10.0.2.15
      - MASTERHOST=10.0.2.15
    volumes:
      - "../../redis-data/redis3:/data"
    restart: always
